<a href="https://colab.research.google.com/github/Ankita2003-amt/dv/blob/main/ds_practical_03.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Practical no_03:**
i. Write a NumPy program to count the number of dimensions,
number
of elements and number of bytes for each element in a given
array.

In [5]:
import numpy as np
array_1=np.array([[1,2],[4,5]])
array_1

array([[1, 2],
       [4, 5]])

In [7]:
array_1.itemsize

8

In [8]:
array_1.ndim

2

3.2.
ii. Write a NumPy program to get a copy of a matrix with the
elements below the k-th diagonal zeroed.

In [12]:
import numpy as np
m=np.matrix([[1,2,3],[4,5,6],[7,8,9]])
print("sample matrix")
print(m)
print("\ntriu() function without any parameter:")
print(np.triu(m))
print("\nBelow 1st daigonal Zeroed.")
print(np.triu(m,-1))
print("\nBelow 2nd daigonal Zeroed.")
print(np.triu(m,-2))

sample matrix
[[1 2 3]
 [4 5 6]
 [7 8 9]]

triu() function without any parameter:
[[1 2 3]
 [0 5 6]
 [0 0 9]]

Below 1st daigonal Zeroed.
[[1 2 3]
 [4 5 6]
 [0 8 9]]

Below 2nd daigonal Zeroed.
[[1 2 3]
 [4 5 6]
 [7 8 9]]
